version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: @types/node
    groups:
      dependencies:
        patterns:
          - '*'
