name: 更新预览版文档
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docs:
    name: 构建部署文档站点
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: edge
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 准备 Git 环境
        uses: actions/checkout@v3
      - name: 准备 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: 安装包管理器
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: 恢复缓存
        uses: actions/cache@v2
        with:
          path: node_modules
          key: dependencies
          restore-keys: dependencies
      - name: 安装依赖
        run: |
          pnpm bootstrap
      - name: 构建文档站点
        run: |
          pnpm doc-gen
          pnpm docs:build --base "/api-node-sdk/"
      - name: 设置环境
        uses: actions/configure-pages@v3
      - name: 上传物料
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist
      - name: 发布线上
        id: deployment
        uses: actions/deploy-pages@v1
